
branches:
  only:
  - master
  - /v\d+\.\d+\.\d+(-\d+)?/
  
clone_folder: c:\project\docximport

image:
- Visual Studio 2017

configuration: Release

platform: x64


init:
  # Configure the AppVeyor build version to ${branch-name}-${git-revision}-${timestamp}
  - ps: $commit = $env:appveyor_repo_commit.SubString(0,7)
  - ps: $timestamp = $env:appveyor_repo_commit_timestamp.SubString(0,10)
  - ps: Update-AppveyorBuild -Version ("{0}-{1}-{2}" -f $env:appveyor_repo_branch, $commit, $timestamp)


environment:
  global:
    PYTHON: C:\Python37-x64
    QT: C:\Qt\5.13\msvc2017_64


before_build:
- cmd: |-
    set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
#    python -m pip install --upgrade pip
#    pip3.7 install six

    
build_script:
- cmd: |-
    set PATH=%PYTHON%;%QT%\bin;%PATH%
    python buildplugin --language
 

artifacts:
  - path: '*.zip'
    name: plugin

deploy:
  - provider: GitHub
    auth_token:
      secure: QM747yzK0qkUTP1k/zQXGbxvvWK97YQpC5+6oAX6FTCPI+jYlB2zf4mzdcFj/uPL
    release: DOCXImport $(APPVEYOR_REPO_BRANCH)
    tag: $(APPVEYOR_REPO_BRANCH)
    description: '[Replace this text]'
    artifact: plugin
    draft: true
    on:
      branch: /v\d+\.\d+\.\d+(-\d+)?/

